### ISSUE TITLE
Disapatch timer do not stop.

### ISSUE THREAD

**Issue by pdsavard** [TommasoScalici/AppShell#3]
Hi, do you see some behaviours when using a dispatchTimer inside one view? In the NavigateFrom function, I stop the timer but the timer still running and calling is tick function.

**Comment by TommasoScalici** [comment]
Hi,

sorry but I don't understand what's the issue you're experiencing. Can you please post some code and what result you're expecting? Thanks.

**Comment by TommasoScalici** [comment]
Closing this since it hasn't been active for more than a year.
